from app import db, Orders, Stock

db.drop_all()
db.create_all()


p1 = Stock(manufacturer = 'Kodak', model = 'Portra', exposure = '400', price = '15', in_stock = 'out of stock')
p2 = Stock(manufacturer = 'Kodak', model = 'Ektar', exposure = '100', price = '10', in_stock = 'yes')
p3 = Stock(manufacturer = 'Kodak', model = 'ColourPlus', exposure = '200', price = '6', in_stock = 'yes')
p4 = Stock(manufacturer = 'Fuji', model = 'X-TRA', exposure = '400', price = '15', in_stock = 'yes')
p5 = Stock(manufacturer = 'Fuji', model = 'Colour', exposure = '200', price = '6', in_stock = 'yes')
p6 = Stock(manufacturer = 'Fuji', model = 'Provia', exposure = '100', price = '20', in_stock = 'out of stock')
p7 = Stock(manufacturer = 'Ilford', model = 'HP-5', exposure = '400', price = '4', in_stock = 'yes')
p8 = Stock(manufacturer = 'Ilford', model = 'Delta', exposure = '100', price = '7', in_stock = 'yes')
p9 = Stock(manufacturer = 'Ilford', model = 'SFX', exposure = '200', price = '12', in_stock = 'yes')
db.session.add(p1)
db.session.add(p2)
db.session.add(p3)
db.session.add(p4)
db.session.add(p5)
db.session.add(p6)
db.session.add(p7)
db.session.add(p7)
db.session.add(p8)
db.session.add(p9)
db.session.commit()
